-- MySQL Script generated by MySQL Workbench
-- Thu Jan 19 16:15:01 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema control_service
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema control_service
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `control_service` DEFAULT CHARACTER SET utf8 ;
USE `control_service` ;

-- -----------------------------------------------------
-- Table `control_service`.`vehiculos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `control_service`.`vehiculos` (
  `veh_codigo` INT NOT NULL,
  `veh_tipo` VARCHAR(45) NULL,
  `veh_ano` INT NULL,
  PRIMARY KEY (`veh_codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `control_service`.`mecanicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `control_service`.`mecanicos` (
  `mec_codigo` INT NOT NULL,
  `mec_nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`mec_codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `control_service`.`servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `control_service`.`servicios` (
  `ser_codigo` INT NOT NULL,
  `ser_aceite` VARCHAR(45) NULL DEFAULT 'revisiones, niveles de aceite-liquido de frenos-refrigerante-direccion, cambios de repuestos',
  `veh_codigo` INT NOT NULL,
  `ser_motor` VARCHAR(45) NULL,
  `ser_transmision` VARCHAR(45) NULL,
  `ser_frenos` VARCHAR(45) NULL,
  `ser_refrijerante` VARCHAR(45) NULL,
  `ser_direcion` VARCHAR(45) NULL,
  `ser_fecha` DATE NULL,
  `mec_codigo` INT NOT NULL,
  PRIMARY KEY (`ser_codigo`),
  INDEX `fk_servicios_Vehiculos_idx` (`veh_codigo` ASC) VISIBLE,
  INDEX `fk_servicios_mecanicos1_idx` (`mec_codigo` ASC) VISIBLE,
  CONSTRAINT `fk_servicios_Vehiculos`
    FOREIGN KEY (`veh_codigo`)
    REFERENCES `control_service`.`vehiculos` (`veh_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_servicios_mecanicos1`
    FOREIGN KEY (`mec_codigo`)
    REFERENCES `control_service`.`mecanicos` (`mec_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `control_service`.`seguros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `control_service`.`seguros` (
  `seg_codigo` INT NOT NULL,
  `seg_tipo` VARCHAR(45) NULL DEFAULT 'SOTA, Seguro Contractual, Seguro Extracontractual',
  `seg_fecha_expedicion` DATE NULL,
  `veh_codigo` INT NOT NULL,
  PRIMARY KEY (`seg_codigo`),
  INDEX `fk_seguros_Vehiculos1_idx` (`veh_codigo` ASC) VISIBLE,
  CONSTRAINT `fk_seguros_Vehiculos1`
    FOREIGN KEY (`veh_codigo`)
    REFERENCES `control_service`.`vehiculos` (`veh_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `control_service`.`duenos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `control_service`.`duenos` (
  `due_codigo` INT NOT NULL,
  `due_nombre` VARCHAR(45) NULL,
  `due_telefono` INT NULL,
  `due_correo` VARCHAR(45) NULL,
  PRIMARY KEY (`due_codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `control_service`.`duenos_de_Vehiculos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `control_service`.`duenos_de_Vehiculos` (
  `due_codigo` INT NOT NULL,
  `veh_codigo` INT NOT NULL,
  PRIMARY KEY (`due_codigo`, `veh_codigo`),
  INDEX `fk_duenos_has_Vehiculos_Vehiculos1_idx` (`veh_codigo` ASC) VISIBLE,
  INDEX `fk_duenos_has_Vehiculos_duenos1_idx` (`due_codigo` ASC) VISIBLE,
  CONSTRAINT `fk_duenos_has_Vehiculos_duenos1`
    FOREIGN KEY (`due_codigo`)
    REFERENCES `control_service`.`duenos` (`due_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_duenos_has_Vehiculos_Vehiculos1`
    FOREIGN KEY (`veh_codigo`)
    REFERENCES `control_service`.`vehiculos` (`veh_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `control_service`.`repuestos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `control_service`.`repuestos` (
  `rep_codigo` INT NOT NULL,
  `rep_nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`rep_codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `control_service`.`repuestos_para_servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `control_service`.`repuestos_para_servicios` (
  `rep_codigo` INT NOT NULL,
  `ser_codigo` INT NOT NULL,
  PRIMARY KEY (`rep_codigo`, `ser_codigo`),
  INDEX `fk_repuestos_has_servicios_servicios1_idx` (`ser_codigo` ASC) VISIBLE,
  INDEX `fk_repuestos_has_servicios_repuestos1_idx` (`rep_codigo` ASC) VISIBLE,
  CONSTRAINT `fk_repuestos_has_servicios_repuestos1`
    FOREIGN KEY (`rep_codigo`)
    REFERENCES `control_service`.`repuestos` (`rep_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_repuestos_has_servicios_servicios1`
    FOREIGN KEY (`ser_codigo`)
    REFERENCES `control_service`.`servicios` (`ser_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
